apiVersion: v1
kind: # https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-toppings 
  namespace: guestbook
data:
  topping: sour-cream
  sauceintensity: {{ quote .Values.sauceintensity }}
