apiVersion: v2 
name: datadog
description: Installs the datadog-cluster-agent via helm 
type: application
version: 0.1.0

appVersion: "1.0"

dependencies:
- name: datadog
  version: 3.101.0
  repository: https://helm.datadoghq.com
