datadog:
  apiKeyExistingSecret: datadog-agent
  appKeyExistingSecret: datadog-app
  site: datadoghq.com
  clusterName: k3d-davetron-labs-mbp-03
  processAgent:
    enabled: true
    processCollection: true
  logs:
    enabled: true
    containerCollectAll: true
