datadog:
  apiKeyExistingSecret: datadog
  site: datadoghq.com
  clusterName: k3d-davetron-labs-mbp-06
  agents:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  logs:
    enabled: true
    containerCollectAll: true
