datadog:
  apiKeyExistingSecret: "datadog-agent"
  appKeyExistingSecret: "datadog-app"
  site: datadoghq.com
  clusterName: k3d-davetron-labs-mbp-02
  processAgent:
    enabled: true
    processCollection: true
  clusterAgent:
    enabled: true
    tokenExistingSecret: datadog-agent-cluster-agent
  confd:
    argocd.yaml: |-
      ad_identifiers:
        - datadog-agent-cluster-agent
      init_config:
      instance:
        - app_controller_endpoint: https://localhost:8082/metricsi
  logs:
    enabled: true
    containerCollectAll: true
  tags:
    - "env:dev"
