datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: k3d-davetron-labs-mbp-06
  agents:
    enabled: true
  clusterAgent:
    enabled: true
    tokenExistingSecret: datadog-cluster-agent
  processAgent:
    enabled: true
    processCollection: true
  logs:
    enabled: true
    containerCollectAll: true
