datadog:
  apiKeyExistingSecret: "datadog-agent"
  appKeyExistingSecret: "datadog-app"
  site: datadoghq.com
  clusterName: k3d-davetron-labs-mbp-02
  processAgent:
    enabled: true
    processCollection: true
  clusterAgent:
    enabled: true
    tokenExistingSecret: datadog-agent-cluster-agent
  logs:
    enabled: true
    containerCollectAll: true
  tags:
    - "env:dev"
