datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: k3d-davetron-labs-mbp-06
  processAgent:
    enabled: true
    processCollection: true
  clusterChecks:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
