apiVersion: v1
kind: Service
metadata:
  name: another-nginx
  namespace: argo-demo
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  destination:
    namespace: applications
    server: k3d-davetron-labs-mbp-worker
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
